services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    restart: always
    environment: 
      - discovery.type=single-node
    ports: 
      - 9200:9200
 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    restart: always
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: 
      - 5601:5601

  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
      - '--es.uri=http://elasticsearch:9200'
    restart: always
    ports:
      - 9114:9114